apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: airflow
    spec:
      containers:
        - args:
            - airflow
            - standalone
          env:
            - name: AIRFLOW__API__AUTH_BACKEND
              value: airflow.api.auth.backend.basic_auth
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
          image: airflow
          name: airflow
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
