apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: hadoop
  name: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hadoop
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: hadoop
    spec:
      containers:
        - env:
            - name: CLUSTER_NAME
              value: local-hadoop
          image: hadoop
          name: hadoop
          ports:
            - containerPort: 9870
              protocol: TCP
            - containerPort: 9864
              protocol: TCP
            - containerPort: 8088
              protocol: TCP
            - containerPort: 8042
              protocol: TCP
            - containerPort: 19888
              protocol: TCP
      hostname: hadoop
      restartPolicy: Always
