apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: hive
  name: hive
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: hive
    spec:
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://hadoop:9000
            - name: HIVE_CORE_CONF_hive_metastore_uris
              value: thrift://localhost:9083
            - name: HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName
              value: org.postgresql.Driver
            - name: HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword
              value: "6161"
            - name: HIVE_CORE_CONF_javax_jdo_option_ConnectionURL
              value: jdbc:postgresql://localhost:5432/metastore
            - name: HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName
              value: yalcindoksanbir
          image: hive
          name: hive
          ports:
            - containerPort: 10000
              protocol: TCP
            - containerPort: 10002
              protocol: TCP
            - containerPort: 9083
              protocol: TCP
      restartPolicy: Always
